/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IshopcareChannelTalkIndexImport } from './routes/ishopcare-channel-talk/index'
import { Route as IshopcareChannelTalkReportIndexImport } from './routes/ishopcare-channel-talk/report/index'
import { Route as IshopcareChannelTalkDashboardIndexImport } from './routes/ishopcare-channel-talk/dashboard/index'

// Create/Update Routes

const IshopcareChannelTalkIndexRoute = IshopcareChannelTalkIndexImport.update({
  id: '/ishopcare-channel-talk/',
  path: '/ishopcare-channel-talk/',
  getParentRoute: () => rootRoute,
} as any)

const IshopcareChannelTalkReportIndexRoute =
  IshopcareChannelTalkReportIndexImport.update({
    id: '/ishopcare-channel-talk/report/',
    path: '/ishopcare-channel-talk/report/',
    getParentRoute: () => rootRoute,
  } as any)

const IshopcareChannelTalkDashboardIndexRoute =
  IshopcareChannelTalkDashboardIndexImport.update({
    id: '/ishopcare-channel-talk/dashboard/',
    path: '/ishopcare-channel-talk/dashboard/',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ishopcare-channel-talk/': {
      id: '/ishopcare-channel-talk/'
      path: '/ishopcare-channel-talk'
      fullPath: '/ishopcare-channel-talk'
      preLoaderRoute: typeof IshopcareChannelTalkIndexImport
      parentRoute: typeof rootRoute
    }
    '/ishopcare-channel-talk/dashboard/': {
      id: '/ishopcare-channel-talk/dashboard/'
      path: '/ishopcare-channel-talk/dashboard'
      fullPath: '/ishopcare-channel-talk/dashboard'
      preLoaderRoute: typeof IshopcareChannelTalkDashboardIndexImport
      parentRoute: typeof rootRoute
    }
    '/ishopcare-channel-talk/report/': {
      id: '/ishopcare-channel-talk/report/'
      path: '/ishopcare-channel-talk/report'
      fullPath: '/ishopcare-channel-talk/report'
      preLoaderRoute: typeof IshopcareChannelTalkReportIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/ishopcare-channel-talk': typeof IshopcareChannelTalkIndexRoute
  '/ishopcare-channel-talk/dashboard': typeof IshopcareChannelTalkDashboardIndexRoute
  '/ishopcare-channel-talk/report': typeof IshopcareChannelTalkReportIndexRoute
}

export interface FileRoutesByTo {
  '/ishopcare-channel-talk': typeof IshopcareChannelTalkIndexRoute
  '/ishopcare-channel-talk/dashboard': typeof IshopcareChannelTalkDashboardIndexRoute
  '/ishopcare-channel-talk/report': typeof IshopcareChannelTalkReportIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/ishopcare-channel-talk/': typeof IshopcareChannelTalkIndexRoute
  '/ishopcare-channel-talk/dashboard/': typeof IshopcareChannelTalkDashboardIndexRoute
  '/ishopcare-channel-talk/report/': typeof IshopcareChannelTalkReportIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/ishopcare-channel-talk'
    | '/ishopcare-channel-talk/dashboard'
    | '/ishopcare-channel-talk/report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/ishopcare-channel-talk'
    | '/ishopcare-channel-talk/dashboard'
    | '/ishopcare-channel-talk/report'
  id:
    | '__root__'
    | '/ishopcare-channel-talk/'
    | '/ishopcare-channel-talk/dashboard/'
    | '/ishopcare-channel-talk/report/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IshopcareChannelTalkIndexRoute: typeof IshopcareChannelTalkIndexRoute
  IshopcareChannelTalkDashboardIndexRoute: typeof IshopcareChannelTalkDashboardIndexRoute
  IshopcareChannelTalkReportIndexRoute: typeof IshopcareChannelTalkReportIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IshopcareChannelTalkIndexRoute: IshopcareChannelTalkIndexRoute,
  IshopcareChannelTalkDashboardIndexRoute:
    IshopcareChannelTalkDashboardIndexRoute,
  IshopcareChannelTalkReportIndexRoute: IshopcareChannelTalkReportIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/ishopcare-channel-talk/",
        "/ishopcare-channel-talk/dashboard/",
        "/ishopcare-channel-talk/report/"
      ]
    },
    "/ishopcare-channel-talk/": {
      "filePath": "ishopcare-channel-talk/index.tsx"
    },
    "/ishopcare-channel-talk/dashboard/": {
      "filePath": "ishopcare-channel-talk/dashboard/index.tsx"
    },
    "/ishopcare-channel-talk/report/": {
      "filePath": "ishopcare-channel-talk/report/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
